version: '2'
services:
  dnsserver:
    image: dnsserver
    container_name: dnsserver
    ports:
    - 53:53/udp
    - 53:53/tcp
    - 10000:10000/tcp
    volumes:
    - "./:/data"
    # Allows to automatically start with Docker
    # restart: always
